### ISSUE TITLE
Cross Posting Monitor

### ISSUE THREAD

**Issue by IanKeen** [iosdevelopershq/camille#3]
We would like to detect when someone cross posts.

Some things to consider would be:
- Configurable threshold
- Notifies specific user(s) and/or channel/group (target)
- A summary of the cross post and channels it occurred in
- Bonus: a command to take action, i.e. auto delete all messages

**Comment by aranasaurus** [comment]
Would be nice if the action button message removed itself after an action has been taken.

**Comment by IanKeen** [comment]
Updated to remove buttons for actions that have been performed as well as a list of actions taken
